export const GET_ALL_CONTENT = "GET_ALL_CONTENT";
export const GET_ALL_CONTENT_SUCCESS = "GET_ALL_CONTENT_SUCCESS";
export const GET_ALL_CONTENT_ERROR = "GET_ALL_CONTENT_ERROR";
export const GET_CONTENT_ON_LAUNCH = "GET_CONTENT_ON_LAUNCH";
export const GET_CONTENT_ON_LAUNCH_SUCCESS = "GET_CONTENT_ON_LAUNCH_SUCCESS";
export const GET_CONTENT_ON_LAUNCH_ERROR = "GET_CONTENT_ON_LAUNCH_ERROR";
export const GET_LAUNCH_LAND_CONTENT = "GET_LAUNCH_LAND_CONTENT";
export const GET_LAUNCH_LAND_CONTENT_SUCCESS =
  "GET_LAUNCH_LAND_CONTENT_SUCCESS";
export const GET_LAUNCH_LAND_CONTENT_ERROR = "GET_LAUNCH_LAND_CONTENT_ERROR";
export const GET_ALL_LAUNCHES = "GET_ALL_LAUNCHES";
export const GET_ALL_LAUNCHES_SUCCESS = "GET_ALL_LAUNCHES_SUCCESS";
